### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_count'

### ISSUE THREAD

**Issue by blldd** [RuihongQiu/SR-GNN_PyTorch-Geometric#2]
你好，我运行代码时出现了上述错误，发现时在调用 torch_geometric.data 中的 Data 类时，传入了Data类没有的参数如：  num_count=num_count, edge_count=edge_count等等，请问该怎么解决：）
感谢！

**Comment by RuihongQiu** [comment]
Would you like to append your PyG version and your whole error log here to help to find the problem?

**Comment by blldd** [comment]
> Would you like to append your PyG version and your whole error log here to help to find the problem?

Thank you for your attention:)
My env version is listed as follows:
```
torch                              1.0.1.post2
torch-cluster                      1.2.4
torch-geometric                    1.1.2
```

and my error log:
```
2019-06-16 22:21:24,588 main.py[line:36] Namespace(batch_size=100, dataset='sample', epoch=10, hidden_size=100, l2=1e-05, lr=0.001, lr_dc=0.1, lr_dc_step=3, top_k=20)
Processing...
Traceback (most recent call last):
  File "/home/dedong/pycharmProjects/Emb4RS/models/SR-GNN_PyTorch-Geometric/src/main.py", line 77, in <module>
    main()
  File "/home/dedong/pycharmProjects/Emb4RS/models/SR-GNN_PyTorch-Geometric/src/main.py", line 43, in main
    train_dataset = MultiSessionsGraph(cur_dir + '/../datasets/' + opt.dataset, phrase='train')
  File "/home/dedong/pycharmProjects/Emb4RS/models/SR-GNN_PyTorch-Geometric/src/dataset.py", line 23, in __init__
    super(MultiSessionsGraph, self).__init__(root, transform, pre_transform)
  File "/home/dedong/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "/home/dedong/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 83, in __init__
    self._process()
  File "/home/dedong/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 117, in _process
    self.process()
  File "/home/dedong/pycharmProjects/Emb4RS/models/SR-GNN_PyTorch-Geometric/src/dataset.py", line 97, in process
    in_degree_inv=in_degree_inv, out_degree_inv=out_degree_inv)
TypeError: __init__() got an unexpected keyword argument 'num_count'

Process finished with exit code 1
```

**Comment by RuihongQiu** [comment]
By now I can not figure out why this error occurs. But this kind of initialization is legal as shown in the [documentation](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html) of PyG. I also don't know if it is because of your version of PyG. My testing environment requires PyG 1.2.1 and would you like to upgrade yout PyG package?

**Comment by blldd** [comment]
> By now I can not figure out why this error occurs. But this kind of initialization is legal as shown in the [documentation](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html) of PyG. I also don't know if it is because of your version of PyG. My testing environment requires PyG 1.2.1 and would you like to upgrade yout PyG package?

Yeh, when I upgrade PyG to 1.2.1, it does seem to work for my issue!
THANK YOU AGAIN!

**Comment by RuihongQiu** [comment]
Cheers!
